### ISSUE TITLE
consider passing down sleep inhibit for the host system

### ISSUE THREAD

**Issue by Richardsause** [waydroid/waydroid#740] opened 2023-02-04 16:59 UTC
**Is your feature request related to a problem? Please describe.**
apps, like games and other inhibit sleep on android, but under waydroid that is passed though, making so that the computer sleep on games, it doesn't happen if you're playing using your keyboard, as that is enough to stop the pc from sleeping, but with controllers that wont happen, at least on kwin

**Describe the solution you'd like**
either pass though the sleep inhibit for the host system, or make so that apps tagged as games do that while opened on the foreground, perhaps even add support for gamemode

**Additional context**
tested with the game rally fury, and the j2me emulator

**my specs in case that is kde's fault and not waydroid's**
KDE Plasma 5.26.5
KDE Frameworks 5.102.0
Window manager is Kwin wayland

**Comment by aleasto** [comment] 2023-08-29 19:23
Duplicate of #552

**Closed by aleasto** 2023-08-29 19:23 UTC
