### ISSUE TITLE
No module named 'gbinder'

### ISSUE THREAD

**Issue by NoEnd-yt** [waydroid/waydroid#886] opened 2023-05-05 11:50 UTC
**Describe the bug**
Waydroid doesn't find the `gbinder` module but `python-gbinder` from the Chaotic AUR is installed on my system. This makes Waydroid unable to start.

**Screenshots**

**General information (please complete the following information):**
 - Waydroid tools Version: 1.4.0-2
 - Waydroid Images Version: 1682127058

**Desktop (please complete the following information):**
 - OS: EndeavourOS
 - GPU: AMD Radeon™ RX 5500
 - Kernel version: linux-zen 6.3.1.zen1-1
 - Host mesa version: mesa 23.0.3-1
 - Desktop: Hyprland

**Additional context**
The only log I can give is the traceback. 

**Logs (please upload as file)**
[waydroid_traceback.txt](https://github.com/waydroid/waydroid/files/11405851/waydroid_traceback.txt)

**Comment by cniw** [comment] 2023-05-05 12:07
duplicate of https://github.com/waydroid/waydroid/issues/884

**Comment by NoEnd-yt** [comment] 2023-05-05 12:48
Ah yes the reinstall won't work with Chaotic AUR, I need to install it from the AUR. Thanks for the help! Where can I report this for the Chaotic AUR to update the package?

**Comment by Quackdoc** [comment] 2023-05-05 12:56
https://github.com/chaotic-aur/packages

**Comment by cniw** [comment] 2023-05-05 13:08
Chaotic-AUR is an automated building repo for AUR packages, i think we need to ask the package maintainer on AUR to bump the pkgrel to trigger the automated process works.
https://aur.archlinux.org/packages/python-gbinder#comment-913196

**Comment by rxfrxctxd** [comment] 2023-05-05 18:43
I don't know a lot about Python directly, but cloning the PKGBUILD from the aur and running `makepkg -si` manually made it compile correctly for me.
Didn't when I used `paru` on the package yesterday. Not sure about Chaotic AUR

**Closed** 2023-05-05 21:52 UTC
