### ISSUE TITLE
Multi Window Mode creates a window bigger than the content

### ISSUE THREAD

**Issue by SnoutBug** [waydroid/waydroid#804] opened 2023-03-15 14:10 UTC
**Describe the bug**
When using Multi Window mode, the Android App is displayed correctly, but instead of having a window with the size of the android app, the window has the size of the entire screen.

This does not affect how other native apps work but when the android app is in the foreground, looking glass only shows a single actor when hovering over non focused apps.

**Screenshots**
![image](https://user-images.githubusercontent.com/71790678/225331826-a2ca6b3a-99d9-44fc-964e-609e812edbb4.png)

**General information (please complete the following information):**
 - `waydroid --version 1.4.0`
 - `system_datetime = 1678511853`
 - `vendor_datetime = 1678533717`

**Desktop (please complete the following information):**
 - OS: Fedora Linux 37 (Workstation Edition) x86_64
 - GPU: AMD Ryzen 3 5400U with Radeon Graphics
 - Kernel version: 6.1.18-200.fc37.x86_64
 - Desktop: GNOME Shell 43.3

**Additional context**
This is just a visual inconvenience.

**Comment by DJCrashdummy** [comment] 2023-03-20 16:38
this is a duplicate of #234.

**Closed** 2023-03-21 12:15 UTC
