### ISSUE TITLE
Please add support for Ubuntu 2204

### ISSUE THREAD

**Issue by Hibanaw** [waydroid/waydroid#368] opened 2022-04-30 04:28 UTC
```
The following packages have unmet dependencies:
 python3-gbinder : Depends: python3 (< 3.10) but 3.10.4-0ubuntu2 is to be installed
```
get the dependency problem when using repo hirsute

**Comment by aliceTheGrinseCatz** [comment] 2022-05-03 19:10
That's a general problem. The dependency python3 has a newer version in Ubuntu 22.04 as python3-gbinder needs but this is more a problem of python3-gbinder and should be brought to the attention of its developer so that he updates the package. 
The right position would be here: https://github.com/erfanoabdi/gbinder-python/issues/5

**Comment by walksanatora** [comment] 2022-05-03 22:24
since `python3-gbinder` is coming from the repo.waydro.id source
why not just compile it with the python3.10 support and add that package either seperately
and have it conflict the python3.9 version
also as is the case on my Linux Mint 20.3 laptop `python3` is actually python3.8

**Comment by walksanatora** [comment] 2022-05-03 22:25
![image](https://user-images.githubusercontent.com/47339836/166580017-f16d7d68-fbcd-4673-9c8b-68aa8e290bf9.png)

**Comment by tootbrute** [comment] 2022-05-04 08:50
This is the same as https://github.com/waydroid/waydroid/issues/363
Should merge these issues.

**Comment by kivo360** [comment] 2022-05-07 05:07
I want to follow the issue. Which one will be the main issue?

**Comment by Kushagra-Srivastava** [comment] 2022-05-07 07:52
> ```
> The following packages have unmet dependencies:
>  python3-gbinder : Depends: python3 (< 3.10) but 3.10.4-0ubuntu2 is to be installed
> ```
> 
> get the dependency problem when using repo hirsute

Hey...if you used the command `export $DISTRO="hirsute"` on your 22.04 jammy system, won't that hold true for your full system? Like you would be getting updates from hirsute repos for every application. Please do tell me if I am correct or not!!

**Comment by MrRulf** [comment] 2022-05-18 20:16
> That's a general problem. The dependency python3 has a newer version in Ubuntu 22.04 as python3-gbinder needs but this is more a problem of python3-gbinder and should be brought to the attention of its developer so that he updates the package. The right position would be here: [erfanoabdi/gbinder-python#5](https://github.com/erfanoabdi/gbinder-python/issues/5)

The developer wrote in the issue that python3.10 is supported, but in a newer version so we'd have to build it from source. Doesn't that mean it just has to get updated?

**Comment by suoko** [comment] 2022-06-11 16:03
The container does not have internet connection on 22.04.
I tried enabling dnsmasq and bind-interfaces option but still not connection for waydroid

**Comment by Fornball** [comment] 2022-06-22 18:23
> The container does not have internet connection on 22.04. I tried enabling dnsmasq and bind-interfaces option but still not connection for waydroid

Does the container start for you at all? Can you use android apps offline in it?

**Comment by e-g1gor** [comment] 2022-06-24 09:28
> > The container does not have internet connection on 22.04. I tried enabling dnsmasq and bind-interfaces option but still not connection for waydroid
> 
> Does the container start for you at all? Can you use android apps offline in it?

I don't know about @suoko but myself have the same problem (internet connection on 22.04), and it seems that all works except internet:

```bash
user@hostname:~$ waydroid status
Session:	RUNNING
Container:	RUNNING
Vendor type:	MAINLINE
Session user:	user(1000)
Wayland display:	wayland-0
```

![image](https://user-images.githubusercontent.com/29484330/175504718-3fa3a101-e2f0-4d9d-843a-6822ba903574.png)

**Comment by AdnanHodzic** [comment] 2022-07-07 05:45
Only way I managed to install Waydroid (1.2.1) on Ubuntu 22.04 was to download all .deb files [from this github page](https://github.com/tuxecure/waydroid-builder/releases/tag/ubuntu-22.04) and simply run `sudo dpkg -i *.deb`

**Comment by cniw** [comment] 2022-07-17 13:01
@MrCyjaneK after your PR https://github.com/waydroid/waydroid/pull/450 and https://github.com/waydroid/gbinder-python/pull/1 merged, then i check https://repo.waydro.id/erfan/jammy/

```
Index of /erfan/jammy/

../
libglibutil-dev_1.0.55_amd64.deb                   15-Jul-2022 16:01               11802
libglibutil-dev_1.0.55_arm64.deb                   15-Jul-2022 16:45               11800
libglibutil_1.0.55_amd64.deb                       15-Jul-2022 16:01               27028
libglibutil_1.0.55_arm64.deb                       15-Jul-2022 16:45               26246
waydroid_1.2.1_all.deb                             14-Jul-2022 18:12              208932
```

There is still missing libgbinder and python3-gbinder packages only waydroid and i don't know how libglibutil packages was there because i don't see any PR or commit related to that package in https://github.com/waydroid/libglibutil also i notice libglibutil package version is 1.0.55 (it's too old, still same with the focal repo) while on upstream repo https://github.com/sailfishos/libglibutil version is 1.0.66

**Comment by Fuseteam** [comment] 2022-07-17 15:04
oh boi it seems our https://github.com/waydroid/libglibutil is forked from https://github.com/droidian/libglibutil, instead of from https://github.com/sailfish/libglibutil. the droidian upstream seems to be out of date

**Comment by Fuseteam** [comment] 2022-07-17 15:18
hopefully now it will work

**Comment by Fuseteam** [comment] 2022-07-17 15:19
@aleasto is there a way to check the output of the ci? if this doesn't fix it it would be nice to see the errors

**Comment by MrCyjaneK** [comment] 2022-07-17 15:45
yup there is. hold on

**Comment by Fuseteam** [comment] 2022-07-31 22:04
@MrCyjaneK anything i can do to help debugging the jammy build?

**Comment by khaledmoalla** [comment] 2022-08-14 11:09
i compiled the libgbinder (python 3.10) for you.
[https://www.file.io/yEQR/download/ha8pOVlBg425](https://github.com/erfanoabdi/gbinder-python/issues/url)
you have just to install it (sudo dpkg -i python3-gbinder_0.0.0+git.202207132158_amd64_fixed_python_3.10.deb)
then choose hirsute distro for waydroid repo and install waydroid

**Comment by electrikjesus** [comment] 2022-08-14 23:31
@khaledmoalla , that link does not seem to be up for confirmation.

**Comment by khaledmoalla** [comment] 2022-08-15 01:25
@electrikjesus  https://cloudsync.uol.de/s/mTceC4HXNdPKsCa/download/python3-gbinder_0.0.0+git.202207132158_amd64_fixed_python_3.10.deb

**Comment by electrikjesus** [comment] 2022-08-15 01:44
I can confirm it works, thank you @khaledmoalla . So what was changed?

**Comment by khaledmoalla** [comment] 2022-08-15 06:50
@electrikjesus 
Change log from the 3.9 version of gbinder
modified the control file to authorize installs along python 3.10
and replaced 3.9 compiled .so with the 3.10 one 
then repackaged

**Comment by aleasto** [comment] 2022-08-17 20:51
This is now completed.
Follow the updated instructions at [docs.waydro.id](https://docs.waydro.id/usage/install-on-desktops)
Specifically you can use `DISTRO=ubuntu-latest`

**Closed by aleasto** 2022-08-17 20:51 UTC

**Comment by manyhats-mike** [comment] 2023-02-08 02:38
> > The developer wrote in the issue that python3.10 is supported, but in a newer version so we'd have to build it from source. Doesn't that mean it just has to get updated in the repo?
> 
> Yes, @erfanoabdi still trying to contact the repo maintainer. Please wait for further information.
> 
> If you can't wait, you can build it by yourself. I have 2 automated scripts you can use:
> 
> 1. https://gist.github.com/cniw/7a0220ce8b75368f7f57aa422d3fea97
> 2. https://gist.github.com/cniw/98e204d7dbc73a3fa1bf61629b2a2fc1

Thanks for this!  #2 script worked perfectly for my system.
