### ISSUE TITLE
Failed to get service waydroidplatform, trying again...

### ISSUE THREAD

**Issue by androidu93** [waydroid/waydroid#347] opened 2022-04-03 18:15 UTC
Hello,

When i try to launch waydroid, this message appears

`Failed to get service waydroidplatform, trying again...`

Thanks. (sorry if i have a bad english)

**Comment by lucasew** [comment] 2022-04-04 13:40
Duplicate of #282

**Comment by Luciogi** [comment] 2022-04-04 14:10
Run commands in sequence
`waydroid session start`
`sudo waydroid container start`
`waydroid show-full-ui` here you have to wait for a little while you might see `Failed to get service waydroidplatform, trying again...` it should start waydroid UI

**Comment by lucasew** [comment] 2022-04-05 00:14
Extra note: If you are using a DE/WM that is based on Xorg instead of wayland then use weston

But before running the commands run `export XDG_SESSION_TYPE=wayland`

**Comment by slondr** [comment] 2022-11-04 00:27
@Luciogi's solution (to just wait) doesn't seem to be working on my machine, unless I should be waiting more than a few hours :D

**Comment by Luciogi** [comment] 2022-11-04 13:22
Sorry I cant help anymore with this problem

**Comment by aleasto** [comment] 2022-11-19 16:20
Missing any information

**Closed by aleasto** 2022-11-19 16:20 UTC

**Comment by Luciogi** [comment] 2022-11-19 17:18
https://github.com/waydroid/waydroid/issues/427#issuecomment-1185745452
try this
