### ISSUE TITLE
Please provide this easy setup script for Ubuntu 22.04

### ISSUE THREAD

**Issue by firefoxlover** [waydroid/waydroid#485] opened 2022-08-14 15:06 UTC
On Ubuntu / Kubuntu latest, Waydroid can't be installed. And furthermore, the installation is not as easy as it could be.

I am currently writing a setup script, it just needs a little more work. I currently struggle to get the keyboard-file writable, so mount the folder as writable and chmod the permission.

```
# -------------------------- Waydroid install script -----------------------

# Internet working
# Installing apps working
# Clipboard not working

# 1. Install old version of python3

wget https://cloudsync.uol.de/s/mTceC4HXNdPKsCa/download/python3-gbinder_0.0.0+git.202207132158_amd64_fixed_python_3.10.deb -N -P ~/Waydroid/python3-fix

sudo dpkg -i ~/Waydroid/python3-fix/python3-gbinder_0.0.0+git.202207132158_amd64_fixed_python_3.10.deb

#sudo rm ~/Waydroid/python3-fix/python3-gbinder_0.0.0+git.202207132158_amd64_fixed_python_3.10.deb

# 2. Get wrong repo that works anyways

export DISTRO="hirsute" && \
sudo curl https://repo.waydro.id/waydroid.gpg --output /usr/share/keyrings/waydroid.gpg && \
echo "deb [signed-by=/usr/share/keyrings/waydroid.gpg] https://repo.waydro.id/ $DISTRO main" > ~/waydroid.list && \
sudo mv ~/waydroid.list /etc/apt/sources.list.d/waydroid.list && \
sudo apt update

# 3. install waydroid

sudo apt install waydroid

# 4. Download 700MB of android files

sudo waydroid init

# if download is slow:
#sudo waydroid init -c https://waydroid.bardia.tech/OTA/system -v https://waydroid.bardia.tech/OTA/vendor

# 5. Create an appstarter (Kubuntu only)
# 5.1 Download the icon

wget https://cloudsync.uol.de/s/kr9fX7zQrwWMLFy/download/waydroid.png -N -P ~/Waydroid

# 5.2 write the appstarter (may be optional if the install works right now

echo "[Desktop Entry] \nType=Application \nName=Waydroid \nExec=sudo systemctl start waydroid-container && waydroid show-full-ui \nIcon=~/Waydroid/Waydroid.png" > /usr/share/applications/Waydroid.desktop

# 6. Create shared folders

mkdir ~/Waydroid/Shared

sudo mount --bind ~/Downloads ~/.local/share/waydroid/data/media/0/Download
sudo mount --bind ~/Waydroid/Shared ~/.local/share/waydroid/data/media/0/Documents

# 7. optional: change keyboard language

# 7.1 allow writing permissions
# **_here are some problems_**

sudo mount -o remount,rw /var/lib/

chmod 660 /var/lib/waydroid/rootfs/system/usr/keylayout/Generic.kl

chmod 440 /var/lib/waydroid/rootfs/system/usr/keylayout/Generic.kl

sudo mount -o remount /var/lib/

# 7.2 change the .kl file
# You may change the QWERY layout to what you want. Editing the install script to fit your needs wont be hard.

#sudo nano /var/lib/waydroid/rootfs/system/usr/keylayout/Generic.kl

# 8. Connect wireless ADB

# 9. Install apps
```

Credits to  @khaledmoalla for compiling the old version of python3

**Comment by khaledmoalla** [comment] 2022-08-15 08:44
@firefoxlover 
For colipBoard  to work you should install pyclip
this webpage can be useful for other issues 
https://docs.waydro.id/debugging/troubleshooting

**Comment by aleasto** [comment] 2022-08-16 12:47
Duplicate of #368

**Closed by aleasto** 2022-08-16 12:47 UTC

**Comment by Fuseteam** [comment] 2022-08-19 17:44
it is technically easier now with [sudo deb-get install waydroid](https://github.com/wimpysworld/deb-get/pull/320#issuecomment-1218076734) but i have no idea if it still works atm
