### ISSUE TITLE
issue??

### ISSUE THREAD

**Issue by seasonedsmartness** [waydroid/waydroid#1507] opened 2024-08-09 09:58 UTC
I'm so confused, I've never done something like this before and I have no idea where to go or what I'm doing but I've tried to download waydroid on my steam deck, but it got stuck on the downloading after saying 'let's configure waydroid' so I just closed konsole and tried to download it again, but it just did this ![image](https://github.com/user-attachments/assets/0d123f13-4211-480f-904b-7b448e573a6f)

**Comment by Quackdoc** [comment] 2024-08-10 00:36
This error can sometimes happen with source forge, generally this should be closed as not related, but it will be closed as a duplicate of https://github.com/waydroid/waydroid/issues/1011 

just try again later, maybe delete everything first, you would need to ask on the tool's github page on how to do that.

**Closed by Quackdoc** 2024-08-10 00:36 UTC
Labels: duplicate
