### ISSUE TITLE
Terminal apps don't work with lxc 4.0.11.

### ISSUE THREAD

**Issue by arun54321** [waydroid/waydroid#238] opened 2021-11-24 14:07 UTC
Distro: Arch linux
Waydroid Image: android 11

**Comment by FlorianFranzen** [comment] 2021-11-27 11:50
Termux crashes with `java.lang.RuntimeException: Cannot open /dev/ptmx` for me too.

**Comment by Etaash-mathamsetty** [comment] 2021-12-10 19:35
also having this issue

**Comment by chqoot-vgxu** [comment] 2022-02-09 19:52
The issue is caused by lxc not punting devpts on /dev/pts. I still haven't figured out why it doesn't get mounted though.

A workaround would be to manually mount it with `mount -t devpts -o defaults,mode=644,ptmxmode=666 devpts /dev/pts`

**Comment by Etaash-mathamsetty** [comment] 2022-03-09 02:50
> The issue is caused by lxc not mounting devpts on /dev/pts. I still haven't figured out why it doesn't get mounted though.
> 
> A workaround would be to manually mount it with `mount -t devpts -o defaults,mode=644,ptmxmode=666 devpts /dev/pts`

I looked at the code and am clueless as well

**Comment by Etaash-mathamsetty** [comment] 2022-03-09 02:50
how can i run it on waydroid startup?

**Comment by chqoot-vgxu** [comment] 2022-03-09 07:35
You shouldn't, that's why this is a workaround and not a fix. Unfortunately I didn't have time to investigate further for a real fix

**Comment by Quackdoc** [comment] 2022-07-07 03:26
this should be fixed now

**Comment by Etaash-mathamsetty** [comment] 2022-08-09 19:13
> this should be fixed now

still broken for me on waydroid 1.3.0

**Comment by chqoot-vgxu** [comment] 2022-08-09 19:31
> still broken for me on waydroid 1.3.0 error: cannot open /dev/ptmx
Updating waydroid doesn't necessarily update lxc config. Check if `lxc.pty.max = 10` is present in `/var/lib/waydroid/lxc/waydroid/config`, if not add it manually

**Comment by Etaash-mathamsetty** [comment] 2022-08-09 19:37
> > still broken for me on waydroid 1.3.0 error: cannot open /dev/ptmx
> 
> Updating waydroid doesn't necessarily update lxc config. Check if `lxc.pty.max = 10` is present in `/var/lib/waydroid/lxc/waydroid/config`, if not add it manually

works fine now!

**Closed** 2022-11-19 14:46 UTC
