### ISSUE TITLE
repro for ubuntu 22.04; dependency problem python3-gbinder

### ISSUE THREAD

**Issue by gebim** [waydroid/waydroid#363] opened 2022-04-22 18:59 UTC
The just-released Ubuntu 22.04 is too fresh for the `'hirsute' repro:

```
root@gebi-tablet:/home/gebi# apt install waydroid
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-gbinder : Depends: python3 (< 3.10) but 3.10.4-0ubuntu2 is to be installed
```

**Comment by marsonpl** [comment] 2022-04-26 17:20
I have the same problem on kubuntu 22.04

**Comment by Kushagra-Srivastava** [comment] 2022-05-07 07:47
After adding the repo i get this error:-
`E: The repository 'https://repo.waydro.id jammy Release' does not have a Release file.`
(Just want to try `sudo apt install waydroid`......the output is `E: Unable to locate package waydroid`)

**Comment by Erisfiregamer1** [comment] 2022-05-07 18:27
> After adding the repo i get this error:- `E: The repository 'https://repo.waydro.id jammy Release' does not have a Release file.` (Just want to try `sudo apt install waydroid`......the output is `E: Unable to locate package waydroid`)

Congrats, you fucked your packages up. (Jammy isn't in their package list)
Remove it, add histute, and I'll try to help.

**Comment by cuikho210** [comment] 2022-05-08 17:57
I got the same error on Pop-os 22.04
```sh
The following packages have unmet dependencies:
 python3-gbinder : Depends: python3 (< 3.10) but 3.10.4-0ubuntu2 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by Kushagra-Srivastava** [comment] 2022-05-09 13:06
```
python3-gbinder : Depends: python3 (< 3.10) but 3.10.4-0ubuntu2 is to be installed
E: Unable to correct problems, you have held broken packages.
```


Sheesh...I have the same problem.

**Comment by Kushagra-Srivastava** [comment] 2022-05-09 13:19
For the folks getting this dependency problem

Go here:- https://github.com/waydroid/waydroid/issues/214#issuecomment-1120926304

**Comment by utimukat55** [comment] 2022-05-12 15:49
Will you plan for https://repo.waydro.id/dists/jammy/ instead of https://repo.waydro.id/dists/hirsute/ ?

**Comment by raulchiclano** [comment] 2022-05-14 06:45
https://github.com/waydroid/waydroid/issues/214#issuecomment-1120926304

**Comment by utimukat55** [comment] 2022-05-14 17:51
I think this issue is ... setup waydroid on Ubuntu 22.04 normally. How do we avoid about python3-gbinder package handling. Normally setup is described at https://docs.waydro.id/usage/install-on-desktops . The way is:

- Add waydroid repo (for droidian & ubports, this step can be skipped) Replace DISTRO="bullseye" with your current target. Options: focal, bullseye, hirsute

Are there any plans for installing export DISTRO="jammy" ? Or export DISTRO="hirsute", debuild -uc-us, sudo apt install waydroid -y the same as before.

**Comment by cobalt2727** [comment] 2022-05-25 01:00
Agreed - when can we expect a 22.04 repo? I hardcoded it into my `sources.list` preemptively but it's getting a little annoying seeing this every time I update (I know, I brought it on myself, but...)

```bash
E: The repository 'https://repo.waydro.id jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by vttb16** [comment] 2022-08-10 00:53
Is this still the case as of august 2022?

**Comment by cobalt2727** [comment] 2022-08-10 02:56
@vttb16 it looks like this was resolved as of 3 days ago! https://repo.waydro.id/dists/

@gebim this can *probably* be closed now - I haven't tried installed from this repo yet but I'd assume it should be good to go

**Comment by cniw** [comment] 2022-08-10 04:21
> it looks like this was resolved as of 3 days ago! https://repo.waydro.id/dists/

@cobalt2727 but `Packages` file in `jammy` folder still empty, you can see `Content-Length: 0` here

```
❯ curl -sI https://repo.waydro.id/dists/jammy/main/binary-all/Packages
HTTP/1.1 200 OK
Server: nginx/1.18.0
Date: Wed, 10 Aug 2022 04:08:06 GMT
Content-Type: application/octet-stream
Content-Length: 0
Connection: keep-alive
Last-Modified: Sat, 06 Aug 2022 11:43:14 GMT
ETag: "62ee53d2-0"
Accept-Ranges: bytes
```

**Comment by cobalt2727** [comment] 2022-08-10 10:30
False alarm, sorry about that...

**Comment by aleasto** [comment] 2022-08-17 20:48
Duplicate of #368

**Closed by aleasto** 2022-08-17 20:48 UTC
