### ISSUE TITLE
didnt work

### ISSUE THREAD

**Issue by MaDoTaHa** [waydroid/waydroid#1406] opened 2024-05-13 23:46 UTC
![Screenshot_20240514_024356](https://github.com/waydroid/waydroid/assets/107647085/fdc4b962-2481-41d4-b46e-71ea3165d8b5)

**Comment by null2264** [comment] 2024-05-14 00:26
Seems to be duplicate of GH-669.

**Comment by Quackdoc** [comment] 2024-08-09 00:07
Closing as duplicate of linked issue

**Closed by Quackdoc** 2024-08-09 00:07 UTC
Labels: duplicate
