### ISSUE TITLE
Waydroid Won't Connect Over ADB

### ISSUE THREAD

**Issue by GAP2007** [waydroid/waydroid#479] opened 2022-08-10 13:08 UTC
I can't connect to Waydroid using the command 

``adb connect 192.168.250.112:5555``

it returns 
```
failed to connect to '192.168.250.112:5555': Connection refused
```
I'm using Arch Linux with the Linux-zen Kernel and Connection worked before but it doesn't work now
thanks.

**Comment by typeable-nickname** [comment] 2022-08-17 18:27
are you sure that 192.168.250.112 is device ip?

**Comment by GAP2007** [comment] 2022-08-17 21:47
@typeable-nickname
I mean That's the default one isn't ?!

**Comment by typeable-nickname** [comment] 2022-08-17 21:52
Idk, go check options -> system informations
And there u will see

**Comment by typeable-nickname** [comment] 2022-08-18 18:56
@GAP2007 my device ip is 192.168.240.112,
https://github.com/termux/termux-app/releases/tag/v0.118.0 go install termux app, then check ip with "ifconfig" command

**Comment by danielcarlgarcia** [comment] 2022-09-02 03:11
same issue here , per checking on the logcat adbd is crashing

**Comment by aleasto** [comment] 2022-11-19 18:05
Duplicate of https://github.com/waydroid/waydroid/issues/348

**Closed by aleasto** 2022-11-19 18:05 UTC
