### ISSUE TITLE
Network not working on fedora37 (Using surface-linux kernel)

### ISSUE THREAD

**Issue by mityax** [waydroid/waydroid#809] opened 2023-03-18 15:17 UTC
**Describe the bug**
I freshly installed waydroid using `dnf install waydroid` on my Microsoft Surface device running Fedora37, used the standard system & vendor urls from the website and it works pretty well - except for network connectivity. The symptom when trying to load any web content in any app was just inifinite loading without any progress or timeout.
I tried virtually all related fixes I could find on the internet, especially those in #143.

Fedora37 by default uses `systemd-resolved`, but I also tried enabling `dnsmasq` instead – however, this always resulted in errors in `waydroid-net.sh`.

**Screenshots**
This icon is visible in the top bar, not sure what it means:
![image](https://user-images.githubusercontent.com/18172993/226113649-db96fc82-6a00-45f4-b3bd-7b4e43499d7d.png)

**General information (please complete the following information):**
 - Waydroid tools Version: 1.4.0 (output of `waydroid --version`)
 - Waydroid Images Version: VANILLA
    - system_datetime = 1678511853
    - vendor_datetime = 1678533717

 

**Desktop (please complete the following information):**
 - OS: Fedora37
 - GPU:Mesa Intel® Xe Graphics (TGL GT2)
 - Kernel version: 6.1.18-200.fc37.x86_64 (surface-linux kernel)
 - Host mesa version: Mesa 22.3.7
 - Desktop: Gnome 43.3
 

**Additional context**
<details><summary><code>ip addr</code> on the host</summary>
<code>
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: wlp0s20f3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 58:ce:2a:d7:31:ab brd ff:ff:ff:ff:ff:ff
    inet 10.11.113.172/24 brd 10.11.113.255 scope global dynamic noprefixroute wlp0s20f3
       valid_lft 171603sec preferred_lft 171603sec
    inet6 fe80::8a92:68bc:97fb:aa17/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:a3:24:e9:fc brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
4: waydroid0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:16:3e:00:00:01 brd ff:ff:ff:ff:ff:ff
    inet 192.168.240.1/24 brd 192.168.240.255 scope global waydroid0
       valid_lft forever preferred_lft forever
    inet6 fe80::216:3eff:fe00:1/64 scope link 
       valid_lft forever preferred_lft forever
5: vethBSGV0I@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master waydroid0 state UP group default qlen 1000
    link/ether fe:bc:24:02:81:ca brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::fcbc:24ff:fe02:81ca/64 scope link 
       valid_lft forever preferred_lft forever
</code>
</details> 

<details><summary><code>ip addr</code> within <code>waydroid shell</code></summary>
<code>
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0@if5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:16:3e:f9:d3:03 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.240.112/24 brd 192.168.240.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::babd:bf5a:7056:4903/64 scope link stable-privacy 
       valid_lft forever preferred_lft forever
</code>
</details> 

**Logs (please upload as file)**
 <details><summary><code>/var/lib/waydroid/waydroid.prop</code></summary>
<code>
sys.use_memfd=true
debug.stagefright.ccodec=0
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
ro.hardware.vulkan=intel
ro.hardware.camera=v4l2
ro.opengles.version=196609
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_x86_64/VANILLA.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
waydroid.tools_version=1.4.0
ro.vndk.lite=true
waydroid.host.user=x
waydroid.host.uid=1000
waydroid.host.gid=1000
waydroid.host_data_path=/home/x/.local/share/waydroid/data
waydroid.xdg_runtime_dir=/run/user/1000
waydroid.pulse_runtime_path=/run/user/1000/pulse
waydroid.wayland_display=wayland-0
waydroid.background_start=false
waydroid.stub_sensors_hal=1
</code>
</details> 

[dmesg.log](https://github.com/waydroid/waydroid/files/11008874/dmesg.log)
[waydroid.log](https://github.com/waydroid/waydroid/files/11008875/waydroid.log)
[waydroid-logcat.log](https://github.com/waydroid/waydroid/files/11008876/waydroid-logcat.log)

**Comment by aleasto** [comment] 2023-03-18 21:51
I also use a surface-linux kernel on fedora.

Do you have docker.service running by any chance?

**Comment by mityax** [comment] 2023-03-19 13:38
Yes I do, is there some problem with that and waydroid?

**Comment by aleasto** [comment] 2023-03-19 13:41
Yes: https://github.com/docker/for-linux/issues/103
Duplicate of #509

**Closed by aleasto** 2023-03-19 13:41 UTC

**Comment by mityax** [comment] 2023-03-19 14:39
Ah great, thanks for pointing me to this!
