### ISSUE TITLE
[Feature Request] Remove app from linux system upon uninstallation

### ISSUE THREAD

**Issue by Aman9das** [waydroid/waydroid#232] opened 2021-11-20 07:06 UTC
Delete the .desktop entry when an app is uninstalled from waydroid.

Also an option to disable the addition of .desktop entries completely would be appreciated..

**Comment by plata** [comment] 2022-03-28 10:39
Duplicate of #203.

**Comment by aleasto** [comment] 2022-11-19 14:29
Duplicate of https://github.com/waydroid/waydroid/issues/203

**Closed by aleasto** 2022-11-19 14:29 UTC
