### ISSUE TITLE
GNOME Activities hang on preview

### ISSUE THREAD

**Issue by Shaarigan** [waydroid/waydroid#660] opened 2022-12-27 17:36 UTC
Hello,

in addition to the issue I already commented on here
https://github.com/waydroid/waydroid/issues/585#issuecomment-1364839020

I experienced another freeze/hang today with the full-ui mode of Waydroid. I opened Waydroid on the default Workspace and then pressed the Super-Key to move the appearing Android window to another workspace. The current GNOME Shell uses Dash to Panel extension to simulate a Windows like Taskbar. The Waydroid process showed up on that Taskbar even when the window isn't showing on the current workspace. I switched forth and back some times and ghen made the mistake to hover over the Waydroid process in Dash to Panel and a preview appeared. After that, the Dash to Panel and Activities menu hang so it couldn't be used anymore. I was however able to start processes from the Desktop and use the Android window to launch Apps etc. but GNOME Shell however didn't respond anymore. I had to open a Terminal to reboot before it worked again.

Waydroid (latest)
Vanilla Images

Lenovo IdeaPad Flex 5 14ALC - Zorin OS 16.2
AMD Ryzen™ 5 5500U Prozessor (Hexa-Core)
16 GB DDR4-3200 SO-DIMM
AMD Radeon RX Vega 7
GNOME Shell

It feels as if the Android window is created in a way that doesn't play well with GNOME Shell and/or it is an issue with Wayland on Zorin OS but everything else works well except for Waydroid.

Would be great if you would fix that!

**Comment by aleasto** [comment] 2023-02-07 19:03
Duplicate of #585
Fixed

**Closed by aleasto** 2023-02-07 19:03 UTC
