### ISSUE TITLE
Application shortcut can't removed automatically after uninstalling app from Waydroid

### ISSUE THREAD

**Issue by Anifyuli** [waydroid/waydroid#611] opened 2022-11-20 23:20 UTC
Hello, dear Waydroid dev teams.
I have a issue and this issue is disturbing convenience using Waydroid. It is app shortcut can't auto remove from host application menu. I wish that issue can solved.
Beside it, I have a requested feature for Waydroid, that feature is management app shortcut (what application exported to host desktop or hide Waydroid app icons from host desktop). Thanks for read this issue and request feature.
I like Waydroid and I use it to replace AVD because my laptop can't run AVD flawlessly. Stay cheers

**Comment by aleasto** [comment] 2022-11-21 11:39
Duplicate of #46 #392

**Closed by aleasto** 2022-11-21 11:39 UTC
