### ISSUE TITLE
Update Android image to version 11 or 12 (LineageOS 18 or 19)

### ISSUE THREAD

**Issue by darkdragon-001** [waydroid/waydroid#456] opened 2022-07-19 21:03 UTC
**Is your feature request related to a problem? Please describe.**
- It would be great to get all the new features
- Probably more/easier compatible with Linux kernel with [Google's upstream first approach](https://arstechnica.com/gadgets/2021/09/android-to-take-an-upstream-first-development-model-for-the-linux-kernel/) (might help with #406?)
- Upgrading smaller steps is easier than bigger steps

**Describe the solution you'd like**
Use LineageOS 19 (Android 12) image by default

**Describe alternatives you've considered**
_None_

**Additional context**
_None_

**Comment by tiol11** [comment] 2022-07-24 16:25
Duplicate of #390

**Closed** 2022-07-25 03:43 UTC
