### ISSUE TITLE
Multi-Window mode: Waydroid crashes with 200% scaling

### ISSUE THREAD

**Issue by PhilDevProg** [waydroid/waydroid#862] opened 2023-04-23 16:33 UTC
**Describe the bug**
Only happens in Multi-Window mode:
This started recently after upgrading to Fedora 38. When I try to start Settings, Waydroid crashes. The same happens when I'm in KDEConnect and tap on the 3-dot-menu of the device. The same happens also in the app Doc Scanner after selecting a file in the file browser. And it also crashes when using a mouse instead of touch.

**General information (please complete the following information):**
 - Waydroid tools Version: 1.4.0
 - Waydroid Images Version: system_datetime = 1682127058/ vendor_datetime = 1682162466

**Desktop (please complete the following information):**
 - OS: Fedora 38
 - GPU: Intel® UHD Graphics 615 (AML-KBL)
 - Kernel version: Linux 6.2.11-1.surface.fc38.x86_64
 - Host mesa version: 23.1.3
 - Desktop: GNOME 44

**Logs (please upload as file)**
 - Prop file, located at `/var/lib/waydroid/waydroid.prop`. In case that doesn't exist, use `/var/lib/waydroid/waydroid_base.prop` instead: 
[waydroid-prop.txt](https://github.com/waydroid/waydroid/files/11304245/waydroid-prop.txt)
 - Log file, located at `/var/lib/waydroid/waydroid.log`: 
[waydroid-log.txt](https://github.com/waydroid/waydroid/files/11304247/waydroid-log.txt)
 - *Full* (not partial) output of `waydroid logcat` while Waydroid is running (this is the crash when tapping on the 3-dot-menu in KDEConnect): 
[logcat.txt](https://github.com/waydroid/waydroid/files/11304259/logcat.txt)
 - Output of `dmesg`: 
[dmesg.txt](https://github.com/waydroid/waydroid/files/11304250/dmesg.txt)

**Comment by aleasto** [comment] 2023-04-23 16:49
Please share `sudo waydroid shell getprop` too

**Comment by PhilDevProg** [comment] 2023-04-23 16:52
> Please share `sudo waydroid shell getprop` too

Here: 
[getprop.txt](https://github.com/waydroid/waydroid/files/11304296/getprop.txt)

**Comment by aleasto** [comment] 2023-04-23 17:02
Posting the relevant bits here:

```
wayland-hwc: wl_surface@173: error 2: Buffer size (469x280) must be an integer multiple of the buffer_scale (2).
```
```
[persist.waydroid.multi_windows]: [true]
[waydroid.display_height]: [1644]
[waydroid.display_scale]: [2]
[waydroid.display_width]: [2562]
[waydroid.full_display_height]: [1280]
[waydroid.full_display_width]: [1920]
```

Odd that this has never come up before.
Fix requires some thinking...

If you need an immediate solution, disabling `multi_windows` would avoid the issue. It is, afterall, an experimental feature.

**Comment by PhilDevProg** [comment] 2023-04-23 17:04
Thanks, I'll try that!

**Comment by Kissycat** [comment] 2023-06-06 13:28
Same here after upgrade gnome to v44.1 on archlinux, when gnome scale is 100%, waydroid is OK, others boot loop, and after disable multi_windows, waydroid works on other scales.

**Comment by Thesola10** [comment] 2023-06-18 20:37
Can confirm identical failure with fractional scaling and multi_windows, likely a GNOME regression since it started happening before I upgraded my Waydroid package

@PhilDevProg you can get Mesa version through renderer info, for instance `glxinfo|grep Mesa` on my system gives 23.1.1

**Comment by mtimms1980** [comment] 2023-09-20 10:27
Are people still facing this issue? I am running Fedora 38 (and Ubuntu 23.04) and cannot use Multi-Window mode regardless of scaling on either.

**Comment by aleasto** [comment] 2023-09-26 12:48
> cannot use Multi-Window mode regardless of scaling on either.

Then clearly this is not your issue.

This should be fixed in the latest OTA update.

**Closed by aleasto** 2023-09-26 12:48 UTC

**Comment by Thesola10** [comment] 2023-09-26 13:30
Can confirm, latest OTA fixed it, thanks! :D

**Comment by mtimms1980** [comment] 2023-09-26 15:09
Well I believe this was my issue, as the OTA update has indeed fixed it. Thank you.
