### ISSUE TITLE
Ubuntu 22.04/jammy repo is broken

### ISSUE THREAD

**Issue by jpmorrison** [waydroid/waydroid#471] opened 2022-07-31 17:52 UTC
Looks like the main repo is broken. The Packages/Packages.gz files are empty. [https://repo.waydro.id/dists/jammy/main/binary-all/Packages](https://repo.waydro.id/dists/jammy/main/binary-all/Packages)

```
sudo apt install waydroid  
Reading package lists... Done  
Building dependency tree... Done  
Reading state information... Done  
E: Unable to locate package waydroid
```

If I download waydroid_1.2.1_all.deb manually it still doesn't install

```
The following packages have unmet dependencies:
 python3-gbinder : Depends: python3 (< 3.9) but 3.10.4-0ubuntu2 is to be installed
E: Unable to correct problems, you have held broken packages.

```

**Comment by aleasto** [comment] 2022-08-05 17:01
Duplicate of #368

**Closed by aleasto** 2022-08-05 17:01 UTC
