### ISSUE TITLE
adb connection refused with waydroid

### ISSUE THREAD

**Issue by partedMagic** [waydroid/waydroid#508] opened 2022-09-02 16:15 UTC
![scrsh](https://user-images.githubusercontent.com/74645668/188195611-0dc81f87-91b4-46ca-bc94-96c3971f7eeb.png)
I just want it to connect so I can mount the partition and root waydroid with magisk. How can I fix this?

Ubuntu 22.04 
5.15.0

**Comment by Hhk78** [comment] 2022-09-03 21:32
Go to developer option in waydroid. Open wireless or network debugging.

**Comment by jhay06** [comment] 2022-09-05 06:57
have the same issue ,  this is failing because , adbd module is crashing on waydroid , waiting for the developer to fix this issue

**Comment by jhay06** [comment] 2022-09-05 07:00
![image](https://user-images.githubusercontent.com/5191437/188384335-b02305bc-bf7c-40a6-8f5d-f7a1c4528b66.png)

**Comment by aleasto** [comment] 2022-11-19 18:05
Duplicate of https://github.com/waydroid/waydroid/issues/348

**Closed by aleasto** 2022-11-19 18:05 UTC
