### ISSUE TITLE
Under volume levels Waydroid appears as "ALSA plug-in [writer]"

### ISSUE THREAD

**Issue by SethFalco** [waydroid/waydroid#572] opened 2022-11-05 09:10 UTC
**Describe the bug**

Waydroid is capable of playing audio, but on the host system it doesn't have a friendly name to be able to pick it out from the sound settings.

Could a better name be provided here please?

Related:
* https://www.mail-archive.com/kde-bugs-dist@kde.org/msg679262.html
* https://www.mail-archive.com/kde-bugs-dist@kde.org/msg678907.html 

**Screenshots**

![image](https://user-images.githubusercontent.com/22801583/200112151-dfb2b8ec-223d-4f38-a002-6739ad871fe5.png)

**General information (please complete the following information):**
 - Waydroid tools Version: 1.3.3
 - Waydroid Images Version: lineage-18.1-20221030-VANILLA-waydroid_x86_64-system.zip

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 11 (bullseye) x86_64
 - GPU: Intel TigerLake GT2 [Iris Xe Graphics]
 - Kernel version: 5.10.0-19-amd64
 - Host mesa version: 
 - Desktop: GNOME Shell 3.38.6

**Additional context**

While exploring Waydroid, I had set a timer which was beeping at me for a while and I had some trouble figuring out where the sound was coming from since in sound settings all it said was "ALSA plug-in [writer]", even after closing all desktop apps the noise went on since Waydroid continues to make noise even when the GUI isn't open.

**Comment by aleasto** [comment] 2022-11-05 21:33
Duplicate of https://github.com/waydroid/android_hardware_waydroid/issues/39

**Closed by aleasto** 2022-11-05 21:33 UTC
