### ISSUE TITLE
[BUG] Waydroid crashes when using app launch

### ISSUE THREAD

**Issue by jkimsis** [waydroid/waydroid#1246] opened 2024-01-19 11:41 UTC
### Describe the bug

If I start waydroid in a weston window, start with show-full-ui and start an app from within LineageOS, it works fine.

If I try to start any app with waydroid app launch, it loads the UI and then crashes.

Has anyone encountered this? I want to be able to start weston and lauch a waydroid app with a shell script.

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

crunchbang++

### Kernel version

Debian 6.1.67-1

### Desktop Environment

Openbox (Crunchbang++)

### GPU

AMD Radeon Vega 8

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`
[dmesg.txt](https://github.com/waydroid/waydroid/files/13988485/dmesg.txt)
[logcat.txt](https://github.com/waydroid/waydroid/files/13988486/logcat.txt)
[waydroid.cfg.txt](https://github.com/waydroid/waydroid/files/13988500/waydroid.cfg.txt)
[waydroid.log.txt](https://github.com/waydroid/waydroid/files/13988501/waydroid.log.txt)
[waydroid.prop.txt](https://github.com/waydroid/waydroid/files/13988506/waydroid.prop.txt)
[waydroid_base.prop.txt](https://github.com/waydroid/waydroid/files/13988507/waydroid_base.prop.txt)

**Comment by aleasto** [comment] 2024-01-19 18:55
Duplicate of #1135

**Closed by aleasto** 2024-01-19 18:55 UTC
