### ISSUE TITLE
[Pinephone] Waydroid interferes with suspend/deep sleep

### ISSUE THREAD

**Issue by kirsle** [waydroid/waydroid#168] opened 2021-10-19 23:16 UTC
I wasn't sure if it was just my device that experienced this problem but some others on Reddit have run into this as well, e.g.: https://www.reddit.com/r/pinephone/comments/qb3vo3/comment/hh77s7p/?context=3

On the Pinephone, the Crust firmware can suspend the phone to deep sleep to conserve battery life.

If the Waydroid session is running, it seems to interfere with deep sleep:

* My phone's suspend TTL is 60 seconds and the phone will go to sleep as normal.
* After several minutes (5 or 10) the screen will turn back on and show my lock screen.
* I can press the power button to turn the screen back off and the phone will nap, but another 5-10 minutes later the screen will turn back on.
* If I don't do anything to it, the screen stays on forever and would eat thru its battery.

If I fully reboot the phone and then _do not_ launch any Android app, suspend works as expected, the phone stays asleep unless the cell modem awakens it.

I saw this on Mobian with Phosh and others have seen it on Manjaro and Arch as well.

**Comment by CalcProgrammer1** [comment] 2021-10-21 06:03
I have this exact behavior on Manjaro.

**Comment by dariox86** [comment] 2021-11-01 12:24
I found out this happens because after five minutes automatic suspension kicks in. Disabling automatic suspension in Phosh "fixes" the issue. Of course this is not a solution but it may help narrowing down the issue.

**Comment by kirsle** [comment] 2021-11-14 19:54
This issue still isn't resolved for me but I have found a workaround that doesn't need me to disable suspend in Phosh completely.

I tried this command but it didn't help:

```
waydroid prop set persist.waydroid.suspend true
```

The workaround for me is to stop Waydroid when I'm done using it. I've added a .desktop launcher to my ~/.local/share/applications for this (found [here](https://forums.ubports.com/topic/6919/waydroid-how-to-shut-it-down/2)):

```ini
[Desktop Entry]
Type=Application
Name=Waydroid Stop
Exec=waydroid session stop
Icon=/usr/lib/waydroid/data/AppIcon.png
```

**Comment by Id2ndR** [comment] 2021-11-15 19:45
The previous workaround works but the downside is that waydroid then need about 2 minutes to start again the next time.

I tried to freeze/unfreeze the waydroid container, but this seems to works only when frozen for a small amount of time. I still have not understand what cause lineage OS to be stuck when the container is frozen for too long.

**Comment by PsychoGame** [comment] 2022-01-10 08:40
Just wanted to let you know this problem unfortunately still persists on Manjaro ARM Phosh Beta 20.<br>
Fully updated and running kernel: 5.15.11-1-MANJARO-ARM<br>

**Comment by kmsgli** [comment] 2022-01-11 01:19
+1 for the same problem.
If this can be fixed and waydroid can sleep with the pinephone this will be a huge game changer for people to daily drive the pine phone. Hoping some type of fix is coming.

**Comment by dos1** [comment] 2022-08-28 08:34
This sounds like a RTC wake is being schedules from inside the container.

**Comment by wryun** [comment] 2022-08-30 23:37
This happens for me on my normal computer as well: once a Waydroid session has started, any 'suspend' won't stick and the computer wakes up ~5 minutes later.

**Comment by dos1** [comment] 2022-12-23 03:35
Two ways to resolve this issue:

1. Drop the `CAP_WAKE_ALARM` capability from the container. This can be achieved by adding `lxc.cap.drop = wake_alarm` to `/var/lib/waydroid/lxc/waydroid/config`. With this, the container has no way to schedule a wake up from suspend anymore. I have tested this on my phone and it appears to do its job.
2. Disable periodic wake ups in healthd service. Haven't tested this, and I'm not sure whether there may be other things requesting wake ups as well (which may be both wanted for stuff like alarm clock, or unwanted if it ends up being used for something that normally would quickly put the system back to suspend).  This can be done with this patch to [health_service.cpp](https://github.com/waydroid/android_hardware_waydroid/blob/487cb761d21fd0bd211fb6c3f70cbd21e8669559/health/health_service.cpp):
```diff
@@ -24,7 +24,10 @@
 using android::hardware::health::V2_0::DiskStats;
 using android::hardware::health::V2_0::StorageInfo;
 
-void healthd_board_init(struct healthd_config*) {}
+void healthd_board_init(struct healthd_config*) {
+  healthd_config->periodic_chores_interval_fast = -1;
+  healthd_config->periodic_chores_interval_slow = -1;
+}
 
 int healthd_board_battery_update(
     struct android::BatteryProperties* battery_props) {
```

**Comment by dos1** [comment] 2022-12-23 04:18
Looks like option 1 can cause bootloops due to zygote process crashing.

**Comment by aleasto** [comment] 2023-01-02 00:39
> Looks like option 1 can cause bootloops due to zygote process crashing.

I've been trying dropping CAP_WAKE_ALARM and couldn't reproduce your crash.

**Comment by benpocalypse** [comment] 2023-01-19 19:58
I'm sorry to chime in on this ticket, but I'm running Mobian with Phosh on my Pinephone Pro, and when I try updating my waydroid config with the "lxc.cap.drop = wake_alarm" on version 1.3.4 of Waydroid, then Waydroid will fail to start claiming that it can't parse the config. If I comment the line out, it starts normally.

Is this lxc capability not supported anymore? I can check in with the Mobian folks as well, but thought it was worth adding that here.

**Comment by dos1** [comment] 2023-01-19 20:34
Here's how to do it: https://github.com/waydroid/waydroid/pull/675/files

No need to bother though, you'll end up with a bootloop anyway. It needs patches on the Android side.

**Comment by skoruppa** [comment] 2023-02-08 06:19
Can confirm the issue on a laptop with Ubuntu 22.04. After closing my computer's lid with waydroid session running, it will go to suspend for about 5 to 10 minutes and then wake up even though the lid is still closed

**Comment by PhilDevProg** [comment] 2023-03-09 07:38
This still happens on my Surface Go 3 with Fedora...

**Comment by skoruppa** [comment] 2023-03-09 08:13
@aleasto why is this closed? waydroid/android_hardware_waydroid/pull/45 did not resolve this and issue still occurs

**Comment by aleasto** [comment] 2023-03-13 00:54
I had to track down this bug: https://android-review.googlesource.com/c/platform/frameworks/base/+/2483735

With that figured out I've now re-enabled the fix for the next scheduled OTA (saturday)

**Closed** 2023-03-19 11:46 UTC

**Comment by raingloom** [comment] 2023-09-19 23:10
For some reason it still keeps my phone awake.  I have Signal installed and that uses a notification to keep running when Google Play Services are not installed, but disabling that notification doesn't seem to fix the issue.
