### ISSUE TITLE
[Bug] android.hardware.graphics.composer@2.1-service keeps crashing

### ISSUE THREAD

**Issue by Heus-Sueh** [waydroid/waydroid#608] opened 2022-11-20 00:52 UTC
**Describe the bug**
android.hardware.graphics.composer@2.1-service keeps crashing

**Screenshots**
![image](https://user-images.githubusercontent.com/98482469/202877371-0c4f9072-27ab-4704-b3ba-617e862f50f0.png)

**General information (please complete the following information):**
 - Waydroid tools Version [e.g. 1.1.0]
 - Waydroid Images Version [e.g. VANILLA 20211021]

**Desktop (please complete the following information):**
 ![image](https://user-images.githubusercontent.com/98482469/202877425-61797a38-f1cd-47c0-8408-047001ff1434.png)
![image](https://user-images.githubusercontent.com/98482469/202877484-89452afc-0535-46b2-a0a0-93effa6e206c.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 3a]
 - OS: [e.g. Ubuntu touch OTA19]
 - Mainline or Halium [e.g. Halium 9]
 - Kernel version: [e.g. 4.14.x]

**Additional context**

**Logs (please upload as file)**
 - Prop file, located on `/var/lib/waydroid/waydroid_base.prop`
 ![image](https://user-images.githubusercontent.com/98482469/202877556-1a2d24af-af8e-4803-852c-451972ccfad4.png)

- Output of `waydroid log`
 [waydroid.log](https://github.com/waydroid/waydroid/files/10048201/waydroid.log)

- *Full* (not partially) Output of `waydroid logcat` from the beginning of starting waydroid services

**Comment by aleasto** [comment] 2022-11-21 11:42
Duplicate of #576

**Closed by aleasto** 2022-11-21 11:42 UTC
