### ISSUE TITLE
Mouse pointer is invisible in windowed mode

### ISSUE THREAD

**Issue by mscatloaf** [waydroid/waydroid#255] opened 2021-12-20 20:02 UTC
Issue: when I move my mouse over any waydroid android app it becomes invisible. I can still interact with the app as if my cursor was there, I just cannot see my cursor. When I run waydroid show-full-ui My mouse pointer becomes visible, but then I can no longer have apps outside of the waydroid window. (ie on another desktop.) If I try to open apps from latte-dock (or any other place other than in waydroid) the full ui disappears and my mouse becomes invisible an waydroid windows again.

Expected behavior: when I move my mouse over a waydroid/android app I either see the cursor you see in show-full-ui mode or see my regular cursor that I see over normal Linux apps.

What I have tried:
rebooting
restarting waydroid container
reinstalling waydroid
upgrading waydroid to latest version
upgrading system (yay -Syu)

System information:
OS: EndeavourOS 
Architecture: x86_64
Kernel: 5.15.10-zen1-1-zen 
DE: KDE Plasma 5.23.4
CPU: Intel Core i5-4210m

**Comment by iczero** [comment] 2021-12-28 08:14
Same here. It seems to be an issue specifically with kwin_wayland, as it doesn't happen on gnome. I think someone mentioned that there was a patch somewhere to fix it, not sure where that is.

**Comment by sunfiwtn** [comment] 2022-03-10 18:33
Can confirm that the issue is still present as of kwin 5.24.3

**Comment by oMjF6T3ctfsQg3L** [comment] 2022-03-19 14:04
I can confirm that I still have this issue on manjaro KDE plasma

**Comment by afalout** [comment] 2022-03-19 23:07
Confirming same on KDE Neon current as of today. 
This is making Waydroid unusable on most is not all KDE environments. Is there any chance this may get looked at in the near future?
If not, is there any alternative to Waydroid that works with Wayland and KDE?
Thanks

**Comment by electrikjesus** [comment] 2022-03-19 23:48
We still have to do a deeper analysis of what is happening with the cursor in KDE.

**Comment by kcohar** [comment] 2022-08-20 19:36
Can confirm - this bug occurs with kwin 5.25.4 (KDE Plasma 5.25.4) but not GNOME 42.4

**Comment by sanjay-kr-commit** [comment] 2022-10-26 04:58
this bug still exist
kde plasma 26
kwin 5.26.1

**Comment by rachit1601** [comment] 2022-10-31 18:29
+1

> this bug still exist kde plasma 26 kwin 5.26.1

**Comment by ScrPotato** [comment] 2022-11-04 11:54
I can also confirm.

OS: Arch Linux
Kernel: Linux-Zen 6.0.6
DE: Plasma 5.26.2 
WM: kwin 
waydroid 1.3.3-1

**Comment by aleasto** [comment] 2022-11-05 20:30
We have a workaround, to set `persist.waydroid.cursor_on_subsurface` to `true`
I've added it to the documentation at https://docs.waydro.id/usage/waydroid-prop-options

**Comment by aleasto** [comment] 2022-11-05 20:31
Closing this since I don't forsee this being properly fixed, if not in kwin directly

**Closed by aleasto** 2022-11-05 20:31 UTC

**Comment by dreamlayers** [comment] 2022-11-25 06:13
I have this problem in KDE Plasma 5.25.5. Running `waydroid prop set persist.waydroid.cursor_on_subsurface true` while a session is running, and then stopping the session and starting it again does give me a usable cursor. However, there are two cursors. One is the KDE Plasma cursor on top. If I have a normal Wayland app video overlaying Android, the cursor type that was last present for that window continues on top of the Android window. So, if I move off the edge of the window overlaying Android, it will be the window resizing cursor. The other cursor, below, seems to be drawn on the Android window picture itself. The cursor below is delayed a bit, so that if I move it around quickly, I can see it separate from the cursor on top, and catch up when I slow down or stop moving it. This is a bit distracting, but certainly usable.

**Comment by BlueTree242** [comment] 2024-06-27 20:43
> I have this problem in KDE Plasma 5.25.5. Running `waydroid prop set persist.waydroid.cursor_on_subsurface true` while a session is running, and then stopping the session and starting it again does give me a usable cursor. However, there are two cursors. One is the KDE Plasma cursor on top. If I have a normal Wayland app video overlaying Android, the cursor type that was last present for that window continues on top of the Android window. So, if I move off the edge of the window overlaying Android, it will be the window resizing cursor. The other cursor, below, seems to be drawn on the Android window picture itself. The cursor below is delayed a bit, so that if I move it around quickly, I can see it separate from the cursor on top, and catch up when I slow down or stop moving it. This is a bit distracting, but certainly usable.

I have the same issue

**Comment by Mikaka27** [comment] 2024-06-28 17:23
Doubled cursor is fixed in plasma 5.27 from what I remember.

**Comment by signalno11** [comment] 2024-10-26 16:05
The double cursor is still happening on 6.2 for me
