### ISSUE TITLE
[BUG] WayDroid couldn't install on Debian Sid due to old dependences (polkitd-1 not installable)

### ISSUE THREAD

**Issue by jimed-rand** [waydroid/waydroid#1508] opened 2024-08-10 05:08 UTC
### Describe the bug

![image](https://github.com/user-attachments/assets/91eb8672-8214-4aab-8b5e-0b18465fd679)

Waydroid couldn't install on Debian Sid with newest snapshot (100824-sid) due to old dependence which couldn't support anymore on Debian Sid called `polkitd-1`. These dependences have been deprecated in newest snapshot of Debian Sid. I guess it need to update or Debian Sid users couldn't use Waydroid right now until it's updated. Please help to fixed the bug or do a update with release new version. Gracias 

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Debian Sid (snapshot 100824-sid)

### Kernel version

6.10.3-amd64

### Desktop Environment

GNOME 46 (goes to GNOME 47 beta)

### GPU

Intel UHD 600 (on Intel Celeron N4020)

### Logs

```root@sidneydeb-1405:~# apt install waydroid
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

Unsatisfied dependencies:
 waydroid : Depends: policykit-1 but it is not installable
Error: Unable to correct problems, you have held broken packages.

**Comment by zyxhere** [comment] 2024-08-10 14:15
Already been reported: https://github.com/waydroid/waydroid/issues/1484#issue-2422445211
Can close this issue as its a duplicate

**Comment by aleasto** [comment] 2024-08-10 14:16
Duplicate of #1484

**Closed by aleasto** 2024-08-10 14:16 UTC
