### ISSUE TITLE
Add option to not create .desktop files for Android apps

### ISSUE THREAD

**Issue by kj7rrv** [waydroid/waydroid#271] opened 2022-01-11 15:50 UTC
Would it be too hard to add this feature? I always open Waydroid itself as one window and run Android apps inside it, so having the icons just clutters my Phosh apps menu.

**Comment by kj7rrv** [comment] 2022-01-13 04:39
I found the relevant file, and it looks like I should be able to do this. How should i set it up? Does Waydroid have a configuration file?

**Comment by kj7rrv** [comment] 2022-01-13 04:53
I found the config code as well. If I add this, should I just make it a config option? `no-desktop-files`?

**Comment by electrikjesus** [comment] 2022-01-13 12:31
I think that would be a good addition.

**Comment by electrikjesus** [comment] 2022-01-13 15:59
I would assume it would, yes

**Comment by kj7rrv** [comment] 2022-01-13 16:01
Okay, thanks! When I have time I'll work on this.

Should it back them up somewhere just in case it accidentally deletes something it shouldn't?

**Comment by electrikjesus** [comment] 2022-01-13 18:37
That is also a good idea to have it back up the icons just in case

**Comment by kj7rrv** [comment] 2022-01-15 06:10
I just thought, maybe in addition to this it should offer a way to whitelist apps that will get desktop files? That way preinstalled apps wouldn't clutter the menu, but the ones the user wants would still be available. A blacklist would also work, so newly installed apps would automatically show up.

**Comment by mizzunet** [comment] 2022-01-18 03:39
A workaround is, add to the `NoDisplay=true` `.desktop` files.

`echo NoDisplay=true |  tee -a waydroid.com.android.settings.desktop`

**Comment by kj7rrv** [comment] 2022-01-18 04:36
Thank you @mizzunet! That will definitely help.

**Comment by plata** [comment] 2022-03-28 11:07
Duplicate of #46.

**Comment by Quackdoc** [comment] 2022-05-13 02:15
I think keeping the default of creating desktop entries is fine, and having an opt in whitelist and blacklist would be preferred. 

the default apps shouldn't be blacklisted by default.

**Comment by aleasto** [comment] 2022-11-19 15:25
Duplicate of #46

**Closed by aleasto** 2022-11-19 15:25 UTC

**Comment by GreenLunar** [comment] 2022-12-30 07:30
> A workaround is, add to the `NoDisplay=true` `.desktop` files.
> 
> ```
> cd ~/.local/share/applications
> echo NoDisplay=true |  tee -a waydroid.com.android.settings.desktop
> ```

You can exacute a script to do so for all files start with `waydroid.*` .

However, there are still `.desktop` entries of waydroid programs that were removed.

My solution.

#### When container is always run in the background:
Provide UI to select which program to be displayed/hidden (e.g. AnySoftKeyboard).

#### When container is not starting at boot
Execute `rm .local/share/applications/waydroid.*` upon stopping the container.

**Comment by khamdany** [comment] 2024-06-20 16:37
i create script for this, you just need install fzf.

```
#!/bin/bash

filenames=$(ls $HOME/.local/share/applications/ | grep waydroid)
location="$HOME/.local/share/applications"

marked_filenames=""
for app in $filenames; do
  if grep -q 'NoDisplay=true' "$location/$app"; then
    marked_filenames+="[*] $app\n"
  else
    marked_filenames+="$app\n"
  fi
done

sorted_apps=$(echo -e "$marked_filenames" | sort -t '*' -k 2)

sorted_apps=$(echo -e "$sorted_apps" | sed '/^$/d')

selected_apps=$(echo -e "$sorted_apps"  | fzf --multi)

for app in $selected_apps; do
  if [[ "$app" == "[*]" ]]; then
      continue
  fi
  
  if grep -q 'NoDisplay=true' "$location/$app"; then
    sed -i '/NoDisplay=true/d' "$location/$app"
    echo "[ ] Removed NoDisplay=true from $app"
  else
    sed -i '/\[Desktop Entry\]/a NoDisplay=true' "$location/$app"
    echo "[*] Added NoDisplay=true to $app"
  fi
done

echo "Modified the selected applications."  

```
