### ISSUE TITLE
How to disable Data saver back in waydroid 

### ISSUE THREAD

**Issue by veasnama** [waydroid/waydroid#464] opened 2022-07-28 02:47 UTC
**Describe the bug**
I recently just enabled Data saver in android settings of Waydroid I stuck in loading screen 
didn't know how to exit and read another issue (  Data Saver bricks Android Image #281 )  it said to delete all the data 
How we delete all the data ? 
should uninstall and reinstall waydroid or there is a reset script.
**Screenshots**
![image](https://user-images.githubusercontent.com/47025775/181409027-fd32d564-1f81-481a-8a72-dac0ee525fa8.png)

**General information (please complete the following information):**
 - Waydroid tools Version [e.g. 1.1.0]
 - Waydroid Images Version [e.g. VANILLA 20211021]

**Desktop (please complete the following information):**
veasna@arch
                 `ooo/                 OS: Arch Linux 
                `+oooo:                Kernel: x86_64 Linux 5.18.14-arch1-1
               `+oooooo:               Uptime: 1h 25m
               -+oooooo+:              Packages: 1785
             `/:-:++oooo+:             Shell: zsh 5.9
            `/++++/+++++++:            Resolution: 1920x1080
           `/++++++++++++++:           DE: KDE 5.96.0 / Plasma 5.25.3
          `/+++ooooooooooooo/`         WM: KWin
         ./ooosssso++osssssso+`        GTK Theme: Breeze [GTK2/3]
        .oossssso-````/ossssss+`       Icon Theme: Win11-black
       -osssssso.      :ssssssso.      Disk: 237G / 358G (68%)
      :osssssss/        osssso+++.     CPU: Intel Core i5-8265U @ 8x 3.9GHz [55.0°C]
     /ossssssss/        +ssssooo/-     GPU: Intel Corporation WhiskeyLake-U GT2 [UHD Graphics 620]
   `/ossssso+/:-        -:/+osssso+-   RAM: 6598MiB / 11818MiB

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 3a]
 - OS: [e.g. Ubuntu touch OTA19]
 - Mainline or Halium [e.g. Halium 9]
 - Kernel version: [e.g. 4.14.x]

**Additional context**

**Logs (please upload as file)**
 - Prop file, located on `/var/lib/waydroid/waydroid_base.prop`
 - Output of `waydroid log`
 - *Full* (not partially) Output of `waydroid logcat` from the beginning of starting waydroid services

**Comment by aleasto** [comment] 2022-11-19 15:28
`sudo rm -rf ~/.local/share/waydroid/data`

Closing as duplicate of #281

**Closed by aleasto** 2022-11-19 15:28 UTC
