### ISSUE TITLE
[Feature] Move to a more recent build of LineageOS

### ISSUE THREAD

**Issue by SVTA-OP** [waydroid/waydroid#1337] opened 2024-03-26 12:40 UTC
### Is your feature request related to a problem? Please describe.

LineageOS 18.1 has reached its final builds and is dropping support. Since waydroid is using lineageOS 18.1, some apps and features will no longer be usable.

### Describe the solution you'd like.

I hope the team bumps up the version of LineageOS to version 20 so that the team has more time in case of the next version shutdown.

### Describe alternatives you've considered.

I am aware of possible issues after changing the OS image, but I have tried lineageOS 20 with waydroid and it worked well.

**Comment by Gigas002** [comment] 2024-04-11 11:45
Would you mind sharing a simple how-to for that, as a gist maybe? I'd like to try out this too, but the waydroid wiki instructions on custom android builds seems a bit outdated and I'm a complete newbie when it comes to android.

**Comment by Quackdoc** [comment] 2024-08-09 00:45
This is a wip, closing as duplicate of  https://github.com/waydroid/waydroid/issues/563

**Closed by Quackdoc** 2024-08-09 00:45 UTC
Labels: duplicate

**Comment by solitudealma** [comment] 2024-10-18 15:58
> Would you mind sharing a simple how-to for that, as a gist maybe? I'd like to try out this too, but the waydroid wiki instructions on custom android builds seems a bit outdated and I'm a complete newbie when it comes to android.您介意分享一個簡單的操作方法嗎？我也想嘗試一下，但是關於自訂 android 構建的 waydroid wiki 說明似乎有點過時，而且當涉及到 android 時，我是一個完全的新手。

[this?](http://xlog.insnhgd.com/2)
