### ISSUE TITLE
add nvidia 495.44+ support 

### ISSUE THREAD

**Issue by sl1pkn07** [waydroid/waydroid#278] opened 2022-01-16 02:39 UTC
Hi

nvidia supports wayland/gbm from 495.44 version

please support it

greetings

**Comment by IntinteDAO** [comment] 2022-01-18 17:11
What do you mean. If nvidia supports Wayland, then should be nothing to do with Waydroid.

**Comment by sl1pkn07** [comment] 2022-01-18 17:14
with the normal config. the `show-full-ui` not appears, but change to swifshader like post in Archwiki 

https://wiki.archlinux.org/title/Waydroid#GPU_Requirements

works. so i suppose nvidia is not full supported

**Comment by Quackdoc** [comment] 2022-01-20 02:29
this cannot happen, waydroid uses LXC, and mesa for GPU acceleration. waydroid would need to implement proprietary blobs to get it working, or nouveau support. but I believe nouveau has a lot of issues it'self

**Comment by Varun-garg** [comment] 2022-02-08 09:04
This is a disadvantage from the user's point of view because way droid is supposed to be better than anbox, which apparently supports both xorg and nvidia out of box. Sure we can ask user to buy another GPU, but is that even practical considering global shortages?

**Comment by IntinteDAO** [comment] 2022-02-13 16:32
@Varun-garg 

If you buy Nvidia, you are a "second-class" citizen. Many things run worse on Nvidia.

Or more specifically, on Nvidia drivers. If you use the Nouveau drivers, it will make Waydroid and other things walk properly.

**Comment by sl1pkn07** [comment] 2022-02-13 17:43
> If you buy Nvidia, you are a "second-class" citizen. Many things run worse on Nvidia.

in my POV, make citizes purchase other hardware for use a certain software because refuses to add support, convert that sofware in a "second-class" software

**Comment by IntinteDAO** [comment] 2022-02-13 20:21
@sl1pkn07 

The problem is that Nvidia creates its own solutions instead of using from the normal ones. It's not Waydroid (or any other software) that's doing the mischief.

A bit like being pissed that you won't put fuel in an electric car.

**Comment by IntinteDAO** [comment] 2022-02-13 20:36
@sl1pkn07 If so, Waydroid should work for you with hardware acceleration.

**Comment by sl1pkn07** [comment] 2022-02-13 20:39
well, the waydroid doesn't want to do it, and my KDE is happy with nvidia GBM...

**Comment by IntinteDAO** [comment] 2022-02-13 21:11
@sl1pkn07 Well, you can, but Android won't work on Linux drivers

https://github.com/casualsnek/waydroid_script
You can read about mounting a Waydroid Image here

**Comment by Quackdoc** [comment] 2022-02-13 21:16
If you want to work around the nvidia limitation, look into virpipe, virgl over chroot has worked in the past so it may work here. First and formost, im not a dev, so I cannot speak for them, however you can call waydroid a second class app all you want. it doesn't change the fact that nvidia has historically always been known to have issues with linux. I don't personally see the worth in targeting it. however if you do I would reccomend checking out nvidia LXC setup as it is not the same as mesa.

**Comment by sl1pkn07** [comment] 2022-02-13 21:58
> If you want to work around the nvidia limitation, look into virpipe, virgl over chroot has worked in the past so it may work here. 

thats souds a workground instead of native OOTB

>First and formost, im not a dev, so I cannot speak for them, however you can call waydroid a second class app all you want. it doesn't change the fact that nvidia has historically always been known to have issues with linux. I don't personally see the worth in targeting it. 

for that i say is my POV, the POVs is like the as*, each one have own one ;)

> however if you do I would reccomend checking out nvidia LXC setup as it is not the same as mesa.

like this?

https://theorangeone.net/posts/lxc-nvidia-gpu-passthrough/
https://github.com/lxc/lxc/issues/1629#issuecomment-311379508

in `/var/lib/waydroid/lxc/waydroid/config` 
~~~
# Allow cgroup access
lxc.cgroup.devices.allow: c 195:* rwm
lxc.cgroup.devices.allow: c 243:* rwm
~~~

and `/var/lib/waydroid/lxc/waydroid/config_nodes`

~~~
# Pass through device files
lxc.mount.entry = /dev/nvidia0 dev/nvidia0 none bind,optional,create=file 0 0
lxc.mount.entry = /dev/nvidiactl dev/nvidiactl none bind,optional,create=file 0 0
lxc.mount.entry = /dev/nvidia-uvm dev/nvidia-uvm none bind,optional,create=file 0 0
lxc.mount.entry = /dev/nvidia-modeset dev/nvidia-modeset none bind,optional,create=file 0 0
lxc.mount.entry = /dev/nvidia-uvm-tools dev/nvidia-uvm-tools none bind,optional,create=file 0 0
lxc.mount.entry = /dev/dri/card0 dev/dri/card0 none bind,optional,create=file 0 0
lxc.mount.entry = /dev/dri/renderD128 dev/dri/renderD128 none bind,optional,create=file 0 0
~~~
~~~
└───╼  ls /dev/dri
total 0
drwxrwxrwx   3 root root        100 feb  1 17:23 .
drwxr-xr-x  23 root root       4740 feb 13 19:31 ..
drwxrwxrwx   2 root root         80 feb 13 14:32 by-path
crwxrwxrwx+  1 root video  226,   0 feb 13 14:32 card0
crwxrwxrwx   1 root render 226, 128 feb  1 17:23 renderD128
~~~

**Comment by Quackdoc** [comment] 2022-02-13 22:11
something like that, I don't have much experience with NVIDIA closed source drivers, so you would be entirely on your own. the issue is that I doubt there will ever be a OOTB setup for NVIDIA users until NVIDIA supports mesa.

**Comment by lukts30** [comment] 2022-02-13 22:14
>is possible open the android images (vendor/system img) and inject the missing libraries?

The problem is that Android uses Bionic libc and the Nvidia userspace libraries **require glibc**. You can not even run the NVIDIA drivers on Linux Distribution that do not use glibc (Alpine Linux uses musl libc). 

It might be possible to do but it is not easy because the ABI is just different and the dynamic linker must not confuse the different libc [\[1\]](https://ariadne.space/2021/08/26/there-is-no-such-thing-as-a-glibc-based-alpine-image/).

**Comment by Quackdoc** [comment] 2022-02-13 22:17
which leaves us back to potentially using virpipe I guess

**Comment by kisg** [comment] 2022-02-16 20:25
You could also try to port gcompat to bionic: https://git.adelielinux.org/adelie/gcompat

**Comment by nachfuellbar** [comment] 2022-04-08 16:10
I think it would really be better to address this to nvidia support
There are still many issues when using Nvidia and Wayland
See for example: https://forums.developer.nvidia.com/t/thx-for-gbm-wayland-support-hope-for-rapid-improvements/202556
The user addresses multiple issues in the implementation and hints to some workarounds

When the issues are only for nvidia and persist on many applications - i don't think waydroid would be the one who can really fix this (you can implement workarounds anytime but they need to be verified again and again - and any change from nvidia can break it again)

It would be way more productive to better waydroid in itself than try to fix what's broken not on waydroid's site but on nvidia's

**Comment by vans163** [comment] 2022-04-18 14:43
@sl1pkn07 did you get anywhere with this? Looks like NVIDIA is rolling out more and more plumbing these days.

**Comment by meisme-dev** [comment] 2022-05-13 01:05
the nvidia driver is open source now, should this be possible?

**Comment by Quackdoc** [comment] 2022-05-13 01:27
> the nvidia driver is open source now, should this be possible?

no. kernel driver doesn't matter to us

**Comment by nachfuellbar** [comment] 2022-05-14 10:11
> the nvidia driver is open source now, should this be possible?

Just wanted to explain why this wouldn't do any good (yet) since @Quackdoc didn't mention the reasons:
1) the new "open source" driver of nivida is not anywhere near to be included in linux kernel - it's unlikely this will happening in the near feature
2) this driver focuses on compute loads and graphic cards - you customer devices are supported in "alpha quality" as nvidia says - in other words, it's probably worse than any current solution
3) as far as i read they are still using their proprietary driver in userspace which is the current problem for proper support in waydroid
4) this is a bit of speculation but they are using pretty huge proprietary blobs, so it could be hard to improve it and the way open source userspace driver interact with it

**Comment by Quackdoc** [comment] 2022-05-14 15:10
>     1. the new "open source" driver of nvidia is not anywhere near to be included in linux kernel - it's unlikely this will happening in the near feature

nvidia has already stated they have no plans on getting the driver in it's current state merged into the kernel

`And, no: we don't plan to attempt to upstream the driver here as-is.` as stated on the githubs issue [#19](https://github.com/NVIDIA/open-gpu-kernel-modules/issues/19)

>     2. this driver focuses on compute loads and graphic cards - you customer devices are supported in "alpha quality" as nvidia says - in other words, it's probably worse than any current solution

it's worse but still usable

>     3. as far as i read they are still using their proprietary driver in userspace which is the current problem for proper support in waydroid

this is literally the only thing that matters to us nothing else here is relevant. closed source kernel drivers but open and good and compatible userland drivers would be perfectly fine for use inside of waydroid.

>     4. this is a bit of speculation but they are using pretty huge proprietary blobs, so it could be hard to improve it and the way open source userspace driver interact with it

RHEL has already announced they plan on getting the proprietary userland driver and nouveau to use the same kernel driver. it is possible that this will mean nouveau will become usable on the current cards the new driver supports, but unlikely from the older cards. 

it will as you said, certainly be a lengthy time

**Closed** 2022-08-06 21:05 UTC

**Comment by AlphaCraft9658** [comment] 2024-05-10 18:21
Has anything changed until now? Any new developments in the NVIDIA driver that make implementing GPU acceleration support easier or possible at all? Anything? Or is it still something that is not realistically possible?

**Comment by Quackdoc** [comment] 2024-05-10 18:29
we are pretty much waiting for someone to et NVK working on android, when it does work we will be able to use NVK + Zink for vulkan and gles respectively, or angle, we could use angle instead of zink, both would work

**Comment by AlphaCraft9658** [comment] 2024-05-10 18:49
> we are pretty much waiting for someone to et NVK working on android, when it does work we will be able to use NVK + Zink for vulkan and gles respectively, or angle, we could use angle instead of zink, both would work

I'm unsure whether I'll actually use NVK. Neither am I aware of how it'll work in the future. I'm not sure whether both drivers can coexist and both do their thing, so for certain things that the NVK driver doesn't implement, the proprietary driver could take over, but it's highly unlikely it's actually how it would work. That also means, that the NVK+Zink implementation will probably not work with the proprietary drivers, unless Zink also works with those. I am pretty technical overall, but I don't know all the details, so it would be nice to have a somewhat good impression of how the development of NVIDIA driver support for Waydroid is going, including the proprietary driver.

**Comment by nachfuellbar** [comment] 2024-05-10 19:14
In short - Nvidia has to adhere to standards to make support possible
NVK + Zink is only a possibility thanks to the massive work done by mesa maintainers - not nvidia itself
